---
- hosts: localhost
  tasks:
  - name: Create task definition
    ecs_taskdefinition:
      family: mytestapp
	  revision: REVISION_NO
      containers:
      - name: web
	    memory: 300
        essential: true
        image: "mohanraz/myapachewells"
        mountPoints:
          - containerPath: /var/www/html
            sourceVolume: web_var_www_html
        portMappings:
          - containerPort: 80
            hostPort: 80
	  - name: javabackend
	    memory: 300
        essential: true
        image: "mohanraz/myjavawells"
      volumes:
      - name: web_var_www_html
      state: present
    register: task_output
  - name: Create ECS Service
    ecs_service:
        state: present
        name: test-service
        cluster: weclusters
        task_definition: mytestapp:REVISION_NO
        desired_count: 3
		load_balancers: wordpress
        deployment_configuration:
          minimum_healthy_percent: 50
          maximum_percent: 200
